version: '3.8'

services:
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/database
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    depends_on:
      - db
      
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
