version: '3.8'

services:
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/database
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_MAIN_ENTITIES=1000000
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_MIDDLE_ENTITIES=100000
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_SMALL_ENTITIES=10000
    depends_on:
      - db

  explain-analyze-service:
    build:
      context: ./ExplainAnalyzeService/
      dockerfile: ExplainAnalyzeService/Dockerfile
    volumes:
        - ./explain-analyze-files:/app/explain_analyze_files
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      NUM_ATTEMPTS: "4"
    depends_on:
      - db

  feedback-table-service:
    build:
      context: ./FeedbackTableScript/
      dockerfile: FeedbackTableScript/Dockerfile
    restart: always
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - db

  backup-service:
    build:
      context: ./BackupService/
      dockerfile: BackupService/Dockerfile
    volumes:
      - ./backups:/src/BackupService/backups
    environment:
      BACKUP_DELAY: 1
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      KEEP_BACKUPS: "3"
      BACKUP_DIR: "/src/BackupService/backups"
    entrypoint: sh -c '/etc/init.d/cron start && tail -f /var/log/cron.log'
    depends_on:
      - db
  
  etcd:
    image: quay.io/coreos/etcd:v3.3.8
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      -name etcd0
      -advertise-client-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://0.0.0.0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster etcd0=http://0.0.0.0:2380

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

