version: '3.8'

services:
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/database
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_MAIN_ENTITIES=1000000
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_MIDDLE_ENTITIES=100000
      - FLYWAY_PLACEHOLDERS_CORTAGES_COUNT_SMALL_ENTITIES=10000
    depends_on:
      - db
      
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  explain-analyze-service:
    build:
      context: ./ExplainAnalyzeService/
      dockerfile: ExplainAnalyzeService/Dockerfile
    volumes:
        - ./explain-analyze-files:/app/explain_analyze_files
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      NUM_ATTEMPTS: "4"
    depends_on:
      - db

  feedback-table-service:
    build:
      context: ./FeedbackTableScript/
      dockerfile: FeedbackTableScript/Dockerfile
    restart: always
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - db
